language: ruby
rvm:
  - 1.9.3
  - 2.1.0
  - rbx
  - jruby-19mode
cache: 
  - bundler
  - apt
before_install:
  - sudo apt-get update
  - sudo apt-get install -qq ffmpeg
  - sudo apt-get install -qq aria2